name: le_commercant
description: Application de gestion commerciale pour commerçants

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ── Persistance locale (1re installation / sessions)
  shared_preferences: ^2.2.2

  # ── Fonts Google
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # ── Décommentez si vous ajoutez une police locale
  # fonts:
  #   - family: Nunito
  #     fonts:
  #       - asset: assets/fonts/Nunito-Regular.ttf
  #       - asset: assets/fonts/Nunito-Bold.ttf
  #         weight: 700